version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - /Users/iuk/Volumes/docker/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - tracker

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "5050:8080"
    networks:
      - tracker
    depends_on:
      - postgres

networks:
  tracker:
    driver: bridge

volumes:
    postgres:
    # pgadmin: